### ISSUE TITLE
train.csv

### ISSUE THREAD

**Issue by braveheartwithlove** [myouness/audio_classification#1]
Hello, Friend,
could you please show some file structure example for this part?
like train.csv?

train_files = glob.glob("../input/audio_train/*.wav")
test_files = glob.glob("../input/audio_test/*.wav")
train_labels = pd.read_csv("../input/train.csv")

Thanks

**Comment by CVxTz** [comment]
Hello
That Data is here : https://www.kaggle.com/c/freesound-audio-tagging/data
